/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    courses: Course;
    events: Event;
    teachers: Teacher;
    reviews: Review;
    media: Media;
    subscribers: Subscriber;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    courses: CoursesSelect<false> | CoursesSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    teachers: TeachersSelect<false> | TeachersSelect<true>;
    reviews: ReviewsSelect<false> | ReviewsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    subscribers: SubscribersSelect<false> | SubscribersSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('bg' | 'en') | ('bg' | 'en')[];
  globals: {
    'home-page': HomePage;
    'schedule-page': SchedulePage;
    'dances-page': DancesPage;
    'faq-page': FaqPage;
    'team-page': TeamPage;
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
    'schedule-page': SchedulePageSelect<false> | SchedulePageSelect<true>;
    'dances-page': DancesPageSelect<false> | DancesPageSelect<true>;
    'faq-page': FaqPageSelect<false> | FaqPageSelect<true>;
    'team-page': TeamPageSelect<false> | TeamPageSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: 'bg' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Отделните страници — курсове, танци, всичко, което има свой адрес. Съдържанието се сглобява от блокове.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  /**
   * Малкият текст над заглавието, напр. „Курс“ или „Танц“.
   */
  kicker?: string | null;
  title: string;
  /**
   * Големият текст под заглавието. Едно-две изречения.
   */
  lead?: string | null;
  hero?: {
    type?: ('image' | 'video' | 'none') | null;
    image?: (number | null) | Media;
    /**
     * YouTube или Vimeo адрес.
     */
    videoUrl?: string | null;
    poster?: (number | null) | Media;
  };
  /**
   * Добавяй заглавия, текст, списъци, цитати, снимки и видеа. Влачи ги, за да смениш реда.
   */
  blocks?:
    | (
        | {
            text: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'heading';
          }
        | {
            /**
             * Маркирай дума и натисни иконата за връзка, за да сложиш линк — може към друга страница от сайта или към външен адрес.
             */
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            ordered?: boolean | null;
            items: {
              text: string;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'list';
          }
        | {
            text: string;
            attribution?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'quote';
          }
        | {
            image: number | Media;
            /**
             * Оставиш ли празно, се използва надписът от самия файл.
             */
            caption?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'image';
          }
        | {
            source: 'embed' | 'file' | 'placeholder';
            /**
             * Обикновеният адрес от YouTube или Vimeo — превръща се в плеър автоматично.
             */
            url?: string | null;
            file?: (number | null) | Media;
            /**
             * Снимката, която се вижда, докато видеото не е пуснато.
             */
            poster?: (number | null) | Media;
            caption?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'video';
          }
        | {
            /**
             * Адресът на Google формата или картата. За форма: отвори формата → „Изпрати“ → иконата < > → копирай адреса от src. Може да е различен за български и английски.
             */
            url: string;
            /**
             * Какво е вграденото — чете се от незрящи посетители, които иначе чуват само „рамка“.
             */
            title: string;
            /**
             * Google формите не могат да си кажат височината, затова се задава тук. Вземи числото от кода, който Google дава („Изпрати“ → < >) — то е в height="…". На тесен екран формата става по-висока, така че ако се реже, увеличи числото.
             */
            height?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'embed';
          }
      )[]
    | null;
  cta: {
    label?: string | null;
    /**
     * Определя коя от долните настройки се използва.
     */
    type: 'none' | 'external' | 'page' | 'section' | 'schedule' | 'home';
    /**
     * Пълен адрес, например https://swingbuzz.eu
     */
    url?: string | null;
    page?: (number | null) | Page;
    section?: ('beginners' | 'reviews' | 'dances' | 'faq' | 'events' | 'team' | 'about' | 'contact') | null;
  };
  meta?: {
    /**
     * Оставиш ли празно, се използва заглавието на страницата.
     */
    title?: string | null;
    /**
     * Оставиш ли празно, се използва водещият параграф.
     */
    description?: string | null;
    /**
     * Оставиш ли празно, се използва голямата снимка на страницата.
     */
    image?: (number | null) | Media;
  };
  /**
   * Частта след адреса на сайта, напр. lindi-hop. Оставиш ли го празно, се генерира от заглавието. Смениш ли го на публикувана страница, старите връзки спират да работят.
   */
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Всички снимки и видеа на сайта. Качи оригиналите — размерите за телефон и десктоп се правят автоматично.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Какво се вижда на снимката. Чете се от незрящи посетители и от Google. Остави празно само за чисто декоративни снимки.
   */
  alt?: string | null;
  /**
   * Показва се под снимката, когато блокът го поддържа.
   */
  caption?: string | null;
  /**
   * Не се показва автоматично — за твой архив.
   */
  credit?: string | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    portrait?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    wide?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Групите, които се показват в таблицата на графика и в секция „Начинаещи“. Полетата за дата и цена може да останат празни — тогава се показва бележката до тях („уточнява се“).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses".
 */
export interface Course {
  id: number;
  title: string;
  /**
   * Малкият ред под името в таблицата, напр. „11 класа по 70 минути · без партньор“.
   */
  subtitle?: string | null;
  /**
   * Използва се в картата на началната страница.
   */
  summary?: string | null;
  /**
   * напр. „Начинаещи“
   */
  level?: string | null;
  /**
   * Малките капсули в картата, напр. „11 класа по 70 минути“, „Без партньор“.
   */
  tags?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  /**
   * напр. „11 класа по 70 мин“
   */
  duration?: string | null;
  /**
   * Остави празно, докато датата не е ясна — тогава се показва бележката отдолу.
   */
  startDate?: string | null;
  /**
   * Показва се само когато няма начална дата.
   */
  startNote?: string | null;
  day?: string | null;
  time?: string | null;
  price?: string | null;
  /**
   * напр. „Национален студентски дом, София“
   */
  venue?: string | null;
  /**
   * Как да се напише залата, когато мястото е малко — на началната страница например. Едно-две разпознаваеми думи: „Лозенец“, „Студентски дом“. Празно означава пълното име.
   */
  venueShort?: string | null;
  /**
   * Google Maps адрес на залата.
   */
  mapUrl?: string | null;
  /**
   * Показва се като етикет в картата на началната страница.
   */
  status: 'open' | 'soon' | 'full';
  registration: {
    label?: string | null;
    /**
     * Определя коя от долните настройки се използва.
     */
    type: 'none' | 'external' | 'page' | 'section' | 'schedule' | 'home';
    /**
     * Пълен адрес, например https://swingbuzz.eu
     */
    url?: string | null;
    page?: (number | null) | Page;
    section?: ('beginners' | 'reviews' | 'dances' | 'faq' | 'events' | 'team' | 'about' | 'contact') | null;
  };
  /**
   * Страницата, която се отваря от „Виж курса“.
   */
  page?: (number | null) | Page;
  showOnSchedule?: boolean | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Партита, фестивали и начала на групи. Подреждат се по дата; тези без дата излизат последни. Началната страница показва първите три.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  title: string;
  /**
   * Определя цвета на етикета.
   */
  type: 'festival' | 'party' | 'course' | 'workshop';
  /**
   * Остави празно, докато датата не е ясна. Попълнена дата прави датата в графика връзка „Добави в календара“.
   */
  startsAt?: string | null;
  /**
   * Нужно за връзката към Google Calendar.
   */
  endsAt?: string | null;
  /**
   * Показва се, когато няма начална дата.
   */
  dateNote?: string | null;
  /**
   * По желание. За многодневни събития напиши напр. „25—27 септ. 2026“; иначе датата се форматира автоматично.
   */
  dateLabel?: string | null;
  /**
   * напр. „22:00 — 04:00“ или „часът се уточнява“.
   */
  timeNote?: string | null;
  venue?: string | null;
  mapUrl?: string | null;
  ticket: {
    label?: string | null;
    /**
     * Определя коя от долните настройки се използва.
     */
    type: 'none' | 'external' | 'page' | 'section' | 'schedule' | 'home';
    /**
     * Пълен адрес, например https://swingbuzz.eu
     */
    url?: string | null;
    page?: (number | null) | Page;
    section?: ('beginners' | 'reviews' | 'dances' | 'faq' | 'events' | 'team' | 'about' | 'contact') | null;
  };
  featured?: boolean | null;
  showOnSchedule?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Хората в секция „Екип“. Подреждат се по полето „Ред“.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "teachers".
 */
export interface Teacher {
  id: number;
  /**
   * Както да се покаже на сайта, напр. „Калина К.“
   */
  name: string;
  /**
   * Кратък ред под името, напр. „Линди хоп, Джаз, Степ“.
   */
  disciplines?: string | null;
  /**
   * Портретна снимка (по-висока, отколкото широка). Без снимка се показва плочка с първата буква от името.
   */
  photo?: (number | null) | Media;
  /**
   * Не се показва в решетката — запазено за бъдеща страница на преподавател.
   */
  bio?: string | null;
  active?: boolean | null;
  /**
   * По-малкото число излиза по-напред.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Отзивите в секция „Какво казват танцуващите“. Копирай ги дословно от Google — не ги преразказвай.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews".
 */
export interface Review {
  id: number;
  /**
   * Без кавички — те се добавят от дизайна. Ако отзивът е на български, преводът на английски е по избор.
   */
  quote: string;
  /**
   * Както е в Google. Само първо име също е добре.
   */
  author: string;
  source?: string | null;
  /**
   * По желание — прави името на автора връзка.
   */
  sourceUrl?: string | null;
  published?: boolean | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Имейлите от формата „Кажи ми кога започва“. Пиши на тези хора, когато обявиш нова група.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscribers".
 */
export interface Subscriber {
  id: number;
  email: string;
  locale?: ('bg' | 'en') | null;
  /**
   * Страницата, на която е попълнил формата.
   */
  source?: string | null;
  /**
   * За твои бележки — напр. „писано на 12.09“.
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  /**
   * Редакторите променят съдържание. Администраторите освен това управляват потребители.
   */
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'courses';
        value: number | Course;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'teachers';
        value: number | Teacher;
      } | null)
    | ({
        relationTo: 'reviews';
        value: number | Review;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'subscribers';
        value: number | Subscriber;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  kicker?: T;
  title?: T;
  lead?: T;
  hero?:
    | T
    | {
        type?: T;
        image?: T;
        videoUrl?: T;
        poster?: T;
      };
  blocks?:
    | T
    | {
        heading?:
          | T
          | {
              text?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              content?: T;
              id?: T;
              blockName?: T;
            };
        list?:
          | T
          | {
              ordered?: T;
              items?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        quote?:
          | T
          | {
              text?: T;
              attribution?: T;
              id?: T;
              blockName?: T;
            };
        image?:
          | T
          | {
              image?: T;
              caption?: T;
              id?: T;
              blockName?: T;
            };
        video?:
          | T
          | {
              source?: T;
              url?: T;
              file?: T;
              poster?: T;
              caption?: T;
              id?: T;
              blockName?: T;
            };
        embed?:
          | T
          | {
              url?: T;
              title?: T;
              height?: T;
              id?: T;
              blockName?: T;
            };
      };
  cta?:
    | T
    | {
        label?: T;
        type?: T;
        url?: T;
        page?: T;
        section?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses_select".
 */
export interface CoursesSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  summary?: T;
  level?: T;
  tags?:
    | T
    | {
        label?: T;
        id?: T;
      };
  duration?: T;
  startDate?: T;
  startNote?: T;
  day?: T;
  time?: T;
  price?: T;
  venue?: T;
  venueShort?: T;
  mapUrl?: T;
  status?: T;
  registration?:
    | T
    | {
        label?: T;
        type?: T;
        url?: T;
        page?: T;
        section?: T;
      };
  page?: T;
  showOnSchedule?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  type?: T;
  startsAt?: T;
  endsAt?: T;
  dateNote?: T;
  dateLabel?: T;
  timeNote?: T;
  venue?: T;
  mapUrl?: T;
  ticket?:
    | T
    | {
        label?: T;
        type?: T;
        url?: T;
        page?: T;
        section?: T;
      };
  featured?: T;
  showOnSchedule?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "teachers_select".
 */
export interface TeachersSelect<T extends boolean = true> {
  name?: T;
  disciplines?: T;
  photo?: T;
  bio?: T;
  active?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews_select".
 */
export interface ReviewsSelect<T extends boolean = true> {
  quote?: T;
  author?: T;
  source?: T;
  sourceUrl?: T;
  published?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  credit?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        portrait?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        wide?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscribers_select".
 */
export interface SubscribersSelect<T extends boolean = true> {
  email?: T;
  locale?: T;
  source?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Всяка секция от началната страница, в реда, в който се показва.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: number;
  hero: {
    /**
     * Всеки нов ред тук става нов ред на сайта. Дизайнът е направен за три кратки реда.
     */
    heading: string;
    intro?: string | null;
    photo?: (number | null) | Media;
    primaryCta: {
      label?: string | null;
      /**
       * Определя коя от долните настройки се използва.
       */
      type: 'none' | 'external' | 'page' | 'section' | 'schedule' | 'home';
      /**
       * Пълен адрес, например https://swingbuzz.eu
       */
      url?: string | null;
      page?: (number | null) | Page;
      section?: ('beginners' | 'reviews' | 'dances' | 'faq' | 'events' | 'team' | 'about' | 'contact') | null;
    };
    secondaryCta: {
      label?: string | null;
      /**
       * Определя коя от долните настройки се използва.
       */
      type: 'none' | 'external' | 'page' | 'section' | 'schedule' | 'home';
      /**
       * Пълен адрес, например https://swingbuzz.eu
       */
      url?: string | null;
      page?: (number | null) | Page;
      section?: ('beginners' | 'reviews' | 'dances' | 'faq' | 'events' | 'team' | 'about' | 'contact') | null;
    };
  };
  courseCard?: {
    enabled?: boolean | null;
    badge?: string | null;
    /**
     * Заглавието, описанието и етикетите се вземат от избрания курс. Промениш ли курса, картата се обновява.
     */
    course?: (number | null) | Course;
    linkLabel?: string | null;
  };
  festivalCard: {
    enabled?: boolean | null;
    badge?: string | null;
    dates?: string | null;
    /**
     * Нов ред в текста става нов ред на сайта.
     */
    heading?: string | null;
    body?: string | null;
    logo?: (number | null) | Media;
    link: {
      label?: string | null;
      /**
       * Определя коя от долните настройки се използва.
       */
      type: 'none' | 'external' | 'page' | 'section' | 'schedule' | 'home';
      /**
       * Пълен адрес, например https://swingbuzz.eu
       */
      url?: string | null;
      page?: (number | null) | Page;
      section?: ('beginners' | 'reviews' | 'dances' | 'faq' | 'events' | 'team' | 'about' | 'contact') | null;
    };
  };
  beginners?: {
    enabled?: boolean | null;
    kicker?: string | null;
    /**
     * Нов ред в текста става нов ред на сайта.
     */
    heading?: string | null;
    intro?: string | null;
    /**
     * По една карта за всяка група — начало, ден, час, цена и зала идват от курса. Редът тук е редът на картите. Когато отвориш нова група, добави я тук.
     */
    groups?: (number | Course)[] | null;
    course?: (number | null) | Course;
    /**
     * Води към страницата с подробности за курса.
     */
    courseLinkLabel?: string | null;
    reassuranceHeading?: string | null;
    reassurances?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    signup?: {
      enabled?: boolean | null;
      heading?: string | null;
      body?: string | null;
      placeholder?: string | null;
      buttonLabel?: string | null;
      successMessage?: string | null;
    };
  };
  reviews: {
    enabled?: boolean | null;
    kicker?: string | null;
    /**
     * Нов ред в текста става нов ред на сайта.
     */
    heading?: string | null;
    allLink: {
      label?: string | null;
      /**
       * Определя коя от долните настройки се използва.
       */
      type: 'none' | 'external' | 'page' | 'section' | 'schedule' | 'home';
      /**
       * Пълен адрес, например https://swingbuzz.eu
       */
      url?: string | null;
      page?: (number | null) | Page;
      section?: ('beginners' | 'reviews' | 'dances' | 'faq' | 'events' | 'team' | 'about' | 'contact') | null;
    };
    /**
     * Показва се в трите празни плочки, докато не добавиш истински отзиви в „Отзиви“.
     */
    placeholderNote?: string | null;
  };
  videoStrip: {
    enabled?: boolean | null;
    kicker?: string | null;
    /**
     * Нов ред в текста става нов ред на сайта.
     */
    heading?: string | null;
    handleLink: {
      label?: string | null;
      /**
       * Определя коя от долните настройки се използва.
       */
      type: 'none' | 'external' | 'page' | 'section' | 'schedule' | 'home';
      /**
       * Пълен адрес, например https://swingbuzz.eu
       */
      url?: string | null;
      page?: (number | null) | Page;
      section?: ('beginners' | 'reviews' | 'dances' | 'faq' | 'events' | 'team' | 'about' | 'contact') | null;
    };
    items?:
      | {
          title: string;
          /**
           * Качено mp4. Плочката се пуска на място при клик — нищо не се изтегля, докато посетителят не го поиска. Оставиш ли празно, плочката води към връзката отдолу.
           */
          video?: (number | null) | Media;
          /**
           * Снимката, която се вижда, преди видеото да е пуснато.
           */
          image?: (number | null) | Media;
          /**
           * напр. към клипа в Instagram.
           */
          url?: string | null;
          id?: string | null;
        }[]
      | null;
    note?: string | null;
  };
  dances: {
    enabled?: boolean | null;
    kicker?: string | null;
    /**
     * Нов ред в текста става нов ред на сайта.
     */
    heading?: string | null;
    intro?: string | null;
    introLink: {
      label?: string | null;
      /**
       * Определя коя от долните настройки се използва.
       */
      type: 'none' | 'external' | 'page' | 'section' | 'schedule' | 'home';
      /**
       * Пълен адрес, например https://swingbuzz.eu
       */
      url?: string | null;
      page?: (number | null) | Page;
      section?: ('beginners' | 'reviews' | 'dances' | 'faq' | 'events' | 'team' | 'about' | 'contact') | null;
    };
    /**
     * Всяка карта показва заглавието, водещия параграф и голямата снимка на избраната страница. Редът тук е редът на картите.
     */
    items?: (number | Page)[] | null;
    linkLabel?: string | null;
  };
  faq?: {
    enabled?: boolean | null;
    kicker?: string | null;
    /**
     * Нов ред в текста става нов ред на сайта.
     */
    heading?: string | null;
    items?:
      | {
          question: string;
          answer: string;
          link: {
            label?: string | null;
            /**
             * Определя коя от долните настройки се използва.
             */
            type: 'none' | 'external' | 'page' | 'section' | 'schedule' | 'home';
            /**
             * Пълен адрес, например https://swingbuzz.eu
             */
            url?: string | null;
            page?: (number | null) | Page;
            section?: ('beginners' | 'reviews' | 'dances' | 'faq' | 'events' | 'team' | 'about' | 'contact') | null;
          };
          id?: string | null;
        }[]
      | null;
  };
  events: {
    enabled?: boolean | null;
    kicker?: string | null;
    /**
     * Нов ред в текста става нов ред на сайта.
     */
    heading?: string | null;
    intro?: string | null;
    allLink: {
      label?: string | null;
      /**
       * Определя коя от долните настройки се използва.
       */
      type: 'none' | 'external' | 'page' | 'section' | 'schedule' | 'home';
      /**
       * Пълен адрес, например https://swingbuzz.eu
       */
      url?: string | null;
      page?: (number | null) | Page;
      section?: ('beginners' | 'reviews' | 'dances' | 'faq' | 'events' | 'team' | 'about' | 'contact') | null;
    };
    limit?: number | null;
  };
  team?: {
    enabled?: boolean | null;
    kicker?: string | null;
    /**
     * Нов ред в текста става нов ред на сайта.
     */
    heading?: string | null;
    intro?: string | null;
  };
  about?: {
    enabled?: boolean | null;
    kicker?: string | null;
    /**
     * Нов ред в текста става нов ред на сайта.
     */
    heading?: string | null;
    paragraphs?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    image?: (number | null) | Media;
  };
  contact?: {
    enabled?: boolean | null;
    kicker?: string | null;
    /**
     * Нов ред в текста става нов ред на сайта.
     */
    heading?: string | null;
    intro?: string | null;
  };
  footerCta: {
    heading?: string | null;
    cta: {
      label?: string | null;
      /**
       * Определя коя от долните настройки се използва.
       */
      type: 'none' | 'external' | 'page' | 'section' | 'schedule' | 'home';
      /**
       * Пълен адрес, например https://swingbuzz.eu
       */
      url?: string | null;
      page?: (number | null) | Page;
      section?: ('beginners' | 'reviews' | 'dances' | 'faq' | 'events' | 'team' | 'about' | 'contact') | null;
    };
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Текстовете на страницата с графика. Самите таблици се пълнят от „Курсове и групи“ и „Събития“.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "schedule-page".
 */
export interface SchedulePage {
  id: number;
  kicker?: string | null;
  title: string;
  lead?: string | null;
  groupsHeading?: string | null;
  /**
   * Може да съдържа връзки — маркирай дума и натисни иконата за връзка.
   */
  groupsNote?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  eventsHeading?: string | null;
  emptyNote?: string | null;
  primaryCta: {
    label?: string | null;
    /**
     * Определя коя от долните настройки се използва.
     */
    type: 'none' | 'external' | 'page' | 'section' | 'schedule' | 'home';
    /**
     * Пълен адрес, например https://swingbuzz.eu
     */
    url?: string | null;
    page?: (number | null) | Page;
    section?: ('beginners' | 'reviews' | 'dances' | 'faq' | 'events' | 'team' | 'about' | 'contact') | null;
  };
  secondaryCta: {
    label?: string | null;
    /**
     * Определя коя от долните настройки се използва.
     */
    type: 'none' | 'external' | 'page' | 'section' | 'schedule' | 'home';
    /**
     * Пълен адрес, например https://swingbuzz.eu
     */
    url?: string | null;
    page?: (number | null) | Page;
    section?: ('beginners' | 'reviews' | 'dances' | 'faq' | 'events' | 'team' | 'about' | 'contact') | null;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Страницата с танцовите стилове (/dances).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dances-page".
 */
export interface DancesPage {
  id: number;
  /**
   * Малкият текст над заглавието.
   */
  kicker?: string | null;
  /**
   * Нов ред в текста става нов ред на сайта.
   */
  title: string;
  /**
   * Параграфът под заглавието. Може да остане празен.
   */
  lead?: string | null;
  introLink: {
    label?: string | null;
    /**
     * Определя коя от долните настройки се използва.
     */
    type: 'none' | 'external' | 'page' | 'section' | 'schedule' | 'home';
    /**
     * Пълен адрес, например https://swingbuzz.eu
     */
    url?: string | null;
    page?: (number | null) | Page;
    section?: ('beginners' | 'reviews' | 'dances' | 'faq' | 'events' | 'team' | 'about' | 'contact') | null;
  };
  /**
   * Всяка карта показва заглавието, водещия параграф и голямата снимка на избраната страница. Редът тук е редът на картите.
   */
  items?: (number | Page)[] | null;
  linkLabel?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Често задаваните въпроси (/faq).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq-page".
 */
export interface FaqPage {
  id: number;
  /**
   * Малкият текст над заглавието.
   */
  kicker?: string | null;
  /**
   * Нов ред в текста става нов ред на сайта.
   */
  title: string;
  /**
   * Параграфът под заглавието. Може да остане празен.
   */
  lead?: string | null;
  items?:
    | {
        question: string;
        answer: string;
        link: {
          label?: string | null;
          /**
           * Определя коя от долните настройки се използва.
           */
          type: 'none' | 'external' | 'page' | 'section' | 'schedule' | 'home';
          /**
           * Пълен адрес, например https://swingbuzz.eu
           */
          url?: string | null;
          page?: (number | null) | Page;
          section?: ('beginners' | 'reviews' | 'dances' | 'faq' | 'events' | 'team' | 'about' | 'contact') | null;
        };
        id?: string | null;
      }[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Страницата с екипа (/team). Хората се редактират в „Екип“.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-page".
 */
export interface TeamPage {
  id: number;
  /**
   * Малкият текст над заглавието.
   */
  kicker?: string | null;
  /**
   * Нов ред в текста става нов ред на сайта.
   */
  title: string;
  /**
   * Параграфът под заглавието. Може да остане празен.
   */
  lead?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Лого, контакти, меню и общият бутон „Запиши се“ — важат за целия сайт.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  brandName: string;
  /**
   * Показва се в менюто и долу. Светло лого върху тъмния фон.
   */
  logo?: (number | null) | Media;
  heroBadge?: string | null;
  cta: {
    label: string;
    /**
     * Определя коя от долните настройки се използва.
     */
    type: 'external' | 'page' | 'section' | 'schedule' | 'home';
    /**
     * Пълен адрес, например https://swingbuzz.eu
     */
    url?: string | null;
    page?: (number | null) | Page;
    section?: ('beginners' | 'reviews' | 'dances' | 'faq' | 'events' | 'team' | 'about' | 'contact') | null;
  };
  /**
   * Показва „Записването е отворено“ или „Скоро“ в картата на началната страница.
   */
  registrationOpen?: boolean | null;
  /**
   * напр. +359 88 555 4597
   */
  phone?: string | null;
  email?: string | null;
  addressLine?: string | null;
  venue?: string | null;
  venueMapUrl?: string | null;
  socials?:
    | {
        platform: 'instagram' | 'facebook' | 'youtube' | 'website';
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Редът тук е редът в менюто. Влачи, за да пренаредиш.
   */
  nav?:
    | {
        link: {
          label: string;
          /**
           * Определя коя от долните настройки се използва.
           */
          type: 'external' | 'page' | 'section' | 'schedule' | 'home';
          /**
           * Пълен адрес, например https://swingbuzz.eu
           */
          url?: string | null;
          page?: (number | null) | Page;
          section?: ('beginners' | 'reviews' | 'dances' | 'faq' | 'events' | 'team' | 'about' | 'contact') | null;
        };
        id?: string | null;
      }[]
    | null;
  footerLinks?:
    | {
        link: {
          label: string;
          /**
           * Определя коя от долните настройки се използва.
           */
          type: 'external' | 'page' | 'section' | 'schedule' | 'home';
          /**
           * Пълен адрес, например https://swingbuzz.eu
           */
          url?: string | null;
          page?: (number | null) | Page;
          section?: ('beginners' | 'reviews' | 'dances' | 'faq' | 'events' | 'team' | 'about' | 'contact') | null;
        };
        id?: string | null;
      }[]
    | null;
  footerNote?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        heading?: T;
        intro?: T;
        photo?: T;
        primaryCta?:
          | T
          | {
              label?: T;
              type?: T;
              url?: T;
              page?: T;
              section?: T;
            };
        secondaryCta?:
          | T
          | {
              label?: T;
              type?: T;
              url?: T;
              page?: T;
              section?: T;
            };
      };
  courseCard?:
    | T
    | {
        enabled?: T;
        badge?: T;
        course?: T;
        linkLabel?: T;
      };
  festivalCard?:
    | T
    | {
        enabled?: T;
        badge?: T;
        dates?: T;
        heading?: T;
        body?: T;
        logo?: T;
        link?:
          | T
          | {
              label?: T;
              type?: T;
              url?: T;
              page?: T;
              section?: T;
            };
      };
  beginners?:
    | T
    | {
        enabled?: T;
        kicker?: T;
        heading?: T;
        intro?: T;
        groups?: T;
        course?: T;
        courseLinkLabel?: T;
        reassuranceHeading?: T;
        reassurances?:
          | T
          | {
              text?: T;
              id?: T;
            };
        signup?:
          | T
          | {
              enabled?: T;
              heading?: T;
              body?: T;
              placeholder?: T;
              buttonLabel?: T;
              successMessage?: T;
            };
      };
  reviews?:
    | T
    | {
        enabled?: T;
        kicker?: T;
        heading?: T;
        allLink?:
          | T
          | {
              label?: T;
              type?: T;
              url?: T;
              page?: T;
              section?: T;
            };
        placeholderNote?: T;
      };
  videoStrip?:
    | T
    | {
        enabled?: T;
        kicker?: T;
        heading?: T;
        handleLink?:
          | T
          | {
              label?: T;
              type?: T;
              url?: T;
              page?: T;
              section?: T;
            };
        items?:
          | T
          | {
              title?: T;
              video?: T;
              image?: T;
              url?: T;
              id?: T;
            };
        note?: T;
      };
  dances?:
    | T
    | {
        enabled?: T;
        kicker?: T;
        heading?: T;
        intro?: T;
        introLink?:
          | T
          | {
              label?: T;
              type?: T;
              url?: T;
              page?: T;
              section?: T;
            };
        items?: T;
        linkLabel?: T;
      };
  faq?:
    | T
    | {
        enabled?: T;
        kicker?: T;
        heading?: T;
        items?:
          | T
          | {
              question?: T;
              answer?: T;
              link?:
                | T
                | {
                    label?: T;
                    type?: T;
                    url?: T;
                    page?: T;
                    section?: T;
                  };
              id?: T;
            };
      };
  events?:
    | T
    | {
        enabled?: T;
        kicker?: T;
        heading?: T;
        intro?: T;
        allLink?:
          | T
          | {
              label?: T;
              type?: T;
              url?: T;
              page?: T;
              section?: T;
            };
        limit?: T;
      };
  team?:
    | T
    | {
        enabled?: T;
        kicker?: T;
        heading?: T;
        intro?: T;
      };
  about?:
    | T
    | {
        enabled?: T;
        kicker?: T;
        heading?: T;
        paragraphs?:
          | T
          | {
              text?: T;
              id?: T;
            };
        image?: T;
      };
  contact?:
    | T
    | {
        enabled?: T;
        kicker?: T;
        heading?: T;
        intro?: T;
      };
  footerCta?:
    | T
    | {
        heading?: T;
        cta?:
          | T
          | {
              label?: T;
              type?: T;
              url?: T;
              page?: T;
              section?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "schedule-page_select".
 */
export interface SchedulePageSelect<T extends boolean = true> {
  kicker?: T;
  title?: T;
  lead?: T;
  groupsHeading?: T;
  groupsNote?: T;
  eventsHeading?: T;
  emptyNote?: T;
  primaryCta?:
    | T
    | {
        label?: T;
        type?: T;
        url?: T;
        page?: T;
        section?: T;
      };
  secondaryCta?:
    | T
    | {
        label?: T;
        type?: T;
        url?: T;
        page?: T;
        section?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dances-page_select".
 */
export interface DancesPageSelect<T extends boolean = true> {
  kicker?: T;
  title?: T;
  lead?: T;
  introLink?:
    | T
    | {
        label?: T;
        type?: T;
        url?: T;
        page?: T;
        section?: T;
      };
  items?: T;
  linkLabel?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq-page_select".
 */
export interface FaqPageSelect<T extends boolean = true> {
  kicker?: T;
  title?: T;
  lead?: T;
  items?:
    | T
    | {
        question?: T;
        answer?: T;
        link?:
          | T
          | {
              label?: T;
              type?: T;
              url?: T;
              page?: T;
              section?: T;
            };
        id?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-page_select".
 */
export interface TeamPageSelect<T extends boolean = true> {
  kicker?: T;
  title?: T;
  lead?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  brandName?: T;
  logo?: T;
  heroBadge?: T;
  cta?:
    | T
    | {
        label?: T;
        type?: T;
        url?: T;
        page?: T;
        section?: T;
      };
  registrationOpen?: T;
  phone?: T;
  email?: T;
  addressLine?: T;
  venue?: T;
  venueMapUrl?: T;
  socials?:
    | T
    | {
        platform?: T;
        label?: T;
        url?: T;
        id?: T;
      };
  nav?:
    | T
    | {
        link?:
          | T
          | {
              label?: T;
              type?: T;
              url?: T;
              page?: T;
              section?: T;
            };
        id?: T;
      };
  footerLinks?:
    | T
    | {
        link?:
          | T
          | {
              label?: T;
              type?: T;
              url?: T;
              page?: T;
              section?: T;
            };
        id?: T;
      };
  footerNote?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}